on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - run: echo "lint" 
  format:
    runs-on: ubuntu-latest
    steps:
    - run: echo "format" 
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Unit test" 
  build: 
    runs-on: ubuntu-latest
    needs: [lint, format, unit-test]
    steps:
    - run: pwd
    - run: date
  sit: 
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - run: echo "sit"
  e2e-test: 
    runs-on: ubuntu-latest
    needs: [build, sit]
    steps:
    - run: echo "e2e-test"
  deploy-uat: 
    runs-on: ubuntu-latest
    needs: [e2e-test]
    steps:
    - run: echo "deploy-uat"
  uat: 
    runs-on: ubuntu-latest
    needs: [deploy-uat]
    steps:
    - run: echo "uat"

  deploy-production: 
    runs-on: ubuntu-latest
    needs: [uat]
    steps:
    - run: echo "deploy-production"
  live-testing: 
    runs-on: ubuntu-latest
    needs: [deploy-production]
    steps:
    - run: echo "live-testing"
