name: "CD Pipeline"

on: 
  push:
    branches:
      - main
    tags:
      - v*
  workflow-dispatch:
    inputs:
      message:
        description: 'Optional message to pass to the workflow'
        required: false
        default: 'No custom message provided'

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
    - run: echo "lint" 
  format:
    name: "Format"
    runs-on: ubuntu-latest
    steps:
    - run: echo "format" 
  unit-test:
    name: "Unit test"
    runs-on: ubuntu-latest
    steps:
    - run: echo "Unit test" 
  fat:
    name: "Functional Acceptance Test"
    runs-on: ubuntu-latest
    steps:
    - run: echo "fat" 
  build: 
    name: "Build"
    runs-on: ubuntu-latest
    needs: [lint, format, unit-test, fat]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - run: date

  sit: 
    name: "System Integration Test"
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - run: echo "sit"
  e2e-test: 
    name: "End to End Test"
    runs-on: ubuntu-latest
    needs: [build, sit]
    steps:
    - run: echo "e2e-test"
  deploy-uat: 
    name: "Deploy to UAT"
    runs-on: ubuntu-latest
    needs: [e2e-test]
    steps:
    - run: echo "deploy-uat"
  uat: 
    name: "User Acceptance Test"
    runs-on: ubuntu-latest
    needs: [deploy-uat]
    steps:
    - run: echo "uat"

  deploy-production: 
    name: "Deploy to Production"
    runs-on: ubuntu-latest
    needs: [uat]
    steps:
    - run: echo "deploy-production"
  live-test: 
    name: "Live Test"
    runs-on: ubuntu-latest
    needs: [deploy-production]
    steps:
    - run: echo "live-test"
